server:
  port: 9003
spring:
  application:
    name: cloud-alibaba-provider-9003
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
      eager: true
      filter:
        url-patterns: /**
management:
  endpoints:
    web:
      exposure:
        include: '*'
