server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micah?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: cloud-alibaba-provider-9003
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      server-addr: 127.0.0.1:8848
      file-extension: yaml
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}
#  zipkin:
#    url: http://localhost:9411/api/v2/spans
#    connectTimeout: 5000
#    readTimeout: 10000
#    base-url: http://localhost:9411
#    # 让nacos将它当作一个url，而不是服务名
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1.0
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 127.0.0.1:8080
#      eager: true
#      filter:
#        url-patterns: /**
management:
  endpoints:
    web:
      exposure:
        include: '*'
